S3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.s3Bucket}
    AccessControl: PublicRead
    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: index.html

S3BucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: ${self:custom.s3Bucket}
    PolicyDocument:
      Id: MyPolicy
      Version: '2012-10-17'
      Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: '*'
          Action: 's3:GetObject'
          Resource: 'arn:aws:s3:::${self:custom.s3Bucket}/*'